<?php
/**
 * ShipperHQ
 *
 * @category ShipperHQ
 * @package ShipperHQ\Shipper
 * @copyright Copyright (c) 2015 Zowta LTD and Zowta LLC (http://www.ShipperHQ.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author ShipperHQ Team sales@shipperhq.com
 */

// @codingStandardsIgnoreFile

?>

<?php if ($_item = $block->getItem()): ?>
    <div id="order_item_<?= $block->escapeHtmlAttr($_item->getId()) ?>_carriergroup_shipping" class="product-title">
        <?php echo $block->escapeHtml($block->getCarrierGroupShipping($_item->getId())) ?>
    </div>
<?php endif; ?>
