<?php
/**
 * ShipperHQ
 *
 * @category ShipperHQ
 * @package ShipperHQ\Shipper
 * @copyright Copyright (c) 2015 Zowta LTD and Zowta LLC (http://www.ShipperHQ.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author ShipperHQ Team sales@shipperhq.com
 */

// @codingStandardsIgnoreFile

?>
<?php if ($_item = $block->getItem()): ?>
    <div id="order_item_<?php echo $block->escapeHtmlAttr($_item->getId()) ?>_carriergroup" class="product-title">
        <?php echo $block->escapeHtml($block->getCarrierGroup($_item->getId())) ?>
    </div>
<?php endif; ?>
