<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var ShipperHQ\Shipper\ViewModel\Listing $viewModel */
$viewModel = $block->getData('viewModel');

?>
<script>
    window.shqConfig = <?= /* @escapeNotVerified */ $viewModel->getSerializedConfig() ?>;
</script>
<?php echo $this->getChildHtml('order_shipping_view_orig') ?>
<?php echo $this->getChildHtml('postorder_info') ?>
<?php
if ($viewModel->showListingButton()) {
    echo $this->getChildHtml('shipperhq_shipper_listing_modal');
}
?>

