<?php

/*
 * Shipper HQ
 *
 * @category ShipperHQ
 * @package ShipperHQ_Shipper
 * @copyright Copyright (c) 2020 Zowta LTD and Zowta LLC (http://www.ShipperHQ.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author ShipperHQ Team sales@shipperhq.com
 */


// @codingStandardsIgnoreFile

/** @var ShipperHQ\Shipper\ViewModel\Listing $viewModel */
$viewModel = $block->getData('viewModel');

?>
<script>
    window.shqConfig = <?= /* @escapeNotVerified */ $viewModel->getSerializedConfig() ?>;
</script>
<div class="admin__page-section-item order-shipping-method">
    <style>
        .order-shipping-method > * {
            width: 100%;
        }
    </style>
    <?php echo $this->getChildHtml('order_shipping_view_orig') ?>
    <?php echo $this->getChildHtml('postorder_info') ?>
    <?php echo $this->getChildHtml('shipperhq_orderview_block'); ?>
    <?php
    if ($viewModel->showListingButton()) {
        echo $this->getChildHtml('shipperhq_shipper_listing_modal');
    }
    ?>
</div>
