<?php
/**
 * Shipper HQ
 *
 * @category ShipperHQ
 * @package ShipperHQ_Shipper
 * @copyright Copyright (c) 2020 Zowta LTD and Zowta LLC (http://www.ShipperHQ.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author ShipperHQ Team sales@shipperhq.com
 */

?>
<link rel="shq-carriers-logos-path" href="<?= /* @noEscape */ $block->getViewFileUrl('ShipperHQ_Shipper::images/carriers/') ?>" />
