<?php

/*
 * ShipperHQ
 *
 * @category ShipperHQ
 * @package ShipperHQ\Shipper
 * @copyright Copyright (c) 2020 Zowta LTD and Zowta LLC (http://www.ShipperHQ.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @author ShipperHQ Team sales@shipperhq.com
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\Create\Shipping\Method\Form */ ?>
<?php $_shippingRateGroups = $block->getShippingRates(); ?>
<?php $helper = $this->helper('ShipperHQ\Shipper\Helper\Data'); ?>
<?php if ($_shippingRateGroups): ?>
    <div id="order-shipping-method-choose" class="control">
        <dl class="admin__order-shipment-methods">
            <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
                <dt class="admin__order-shipment-methods-title"><?php echo $block->escapeHtml($block->getCarrierName($code)) ?></dt>
                <dd class="admin__order-shipment-methods-options">
                    <ul class="admin__order-shipment-methods-options-list">
                        <?php foreach ($_rates as $_rate): ?>
                            <?php $_radioProperty = 'name="order[shipping_method]" type="radio"' ?>
                            <?php $_code = $_rate->getCode() ?>
                            <li class="admin__field-option">
                                <?php if ($_rate->getErrorMessage()): ?>
                                    <div class="messages">
                                        <div class="message message-error error">
                                            <div><?php echo $block->escapeHtml($_rate->getErrorMessage()) ?></div>
                                        </div>
                                    </div>
                                <?php else: ?>
                                    <?php $_checked = $block->isMethodActive($_code) ? 'checked="checked"' : '' ?>
                                    <input <?= /* @noEscape */ $_radioProperty ?> value="<?= $block->escapeHtml($_code) ?>"
                                                            id="s_method_<?= $block->escapeHtml($_code) ?>" <?= /* @noEscape */ $_checked ?>
                                                            class="admin__control-radio required-entry"/>
                                    <label class="admin__field-label" for="s_method_<?= $block->escapeHtml($_code) ?>">
                                        <?php echo $block->escapeHtml($_rate->getMethodTitle() ? $_rate->getMethodTitle() : $_rate->getMethodDescription()) ?>
                                        -
                                        <strong>
                                            <?php $_excl = $block->getShippingPrice(
                                                $_rate->getPrice(),
                                                $this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()
                                            ); ?>
                                            <?php $_incl = $block->getShippingPrice($_rate->getPrice(), true); ?>

                                            <?= /* @noEscape */ $_excl ?>
                                            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                                (<?= $block->escapeHtml(__('Incl. Tax')); ?><?= /* @noEscape */ $_incl ?>)
                                            <?php endif; ?>
                                        </strong>
                                    </label>
                                    <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                                        'onclick',
                                        "order.setShippingMethod(this.value)",
                                        'input[id=\'s_method_' . $block->escapeJs($_code) . '\']'
                                    ) ?>
                                <?php endif ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </dd>
            <?php endforeach; ?>
            <?php echo $block->getChildHtml('shipperhq.extra', false); ?>
        </dl>
        <?php if ($helper->adminShippingEnabled()): ?>
            <dt class="admin__order-shipment-methods-title">Custom Shipping</dt>
            <div class="admin__field">
                <label for="customCarrier" class="">Description</label>
                <input name="customCarrier" type="text" id="customCarrier" size="15" class="admin__control-text"/>
            </div>
            <div class="admin__field">
                <label for="customPrice" class="">Price</label>
                <input name="customPrice" type="text" class="admin__control-text input-text validate-zero-or-greater" id="customPrice" size="5" />
            </div>
            <div class="admin__field">
                <button type="button" title="<?= $block->escapeHtml(__('Add custom shipping')) ?>" class="action-default scalable action-secondary"
                        value="shipperadmin_adminshipping" id="shipperadmin_button">
                    <span><?= $block->escapeHtml(__('Add custom shipping')) ?></span>
                </button>
            </div>
            <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                'onclick',
                "order.setAdminShippingMethod('shipperadmin_adminshipping', customCarrier.value, customPrice.value)",
                'button#shipperadmin_button'
            ) ?>
        <?php endif; ?>
    </div>
    <?php $scriptString = <<<script
require(['prototype'], function(){
    $('order-shipping-method-choose').show();
});
script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php elseif ($block->getIsRateRequest()): ?>
    <div class="order-shipping-method-summary">
        <strong class="order-shipping-method-not-available"><?= $block->escapeHtml(__('Sorry, no quotes are available for this order.')) ?></strong>
    </div>
    <br>
    <!--SHQ16-2159 allow custom admin shipping when no rates are displayed -->
    <?php if ($helper->adminShippingEnabled()): ?>
        <dt class="admin__order-shipment-methods-title"><?php echo 'Custom Shipping'; ?></dt>
        <div class="admin__field">
            <label for="customCarrier" class=""><?php echo 'Description'; ?></label>
            <input name="customCarrier" type="text" id="customCarrier" size="15" class="admin__control-text"/>
        </div>
        <div class="admin__field">
            <label for="customPrice" class=""><?php echo 'Price'; ?></label>
            <input name="customPrice" type="text" class="customPrice validate-zero-or-greater" id="customPrice" size="5"
                   class="admin__control-text"/>
        </div>
        <div class="admin__field">
            <button type="button" title="<?= $block->escapeHtml(__('Add custom shipping')) ?>" class="action-default scalable action-secondary"
                    value="shipperadmin_adminshipping" id="shipperadmin_button">
                <span><?= $block->escapeHtml(__('Add custom shipping')) ?></span>
            </button>
        </div>
        <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
            'onclick',
            "order.setAdminShippingMethod('shipperadmin_adminshipping', customCarrier.value, customPrice.value)",
            'button#shipperadmin_button'
        ) ?>
    <?php endif; ?>
<?php else: ?>
    <div id="order-shipping-method-summary" class="order-shipping-method-summary">
        <a href="#" id="loadShippingRates" class="action-default">
            <span><?= $block->escapeHtml(__('Get shipping methods and rates')) ?></span>
        </a>
        <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag('onclick', 'order.loadShippingRates();return false;', '#loadShippingRates'); ?>
        <input type="hidden" name="order[has_shipping]" value="" class="required-entry" />
    </div>
    <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
        'onclick',
        "order.loadShippingRates();event.preventDefault();",
        'div#order-shipping-method-summary a.action-default'
    ) ?>
<?php endif; ?>
<div id="shipping-method-overlay" class="order-methods-overlay">
    <span><?= $block->escapeHtml(__('You don\'t need to select a shipping method.')) ?></span>
</div>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'div#shipping-method-overlay') ?>
<?php $scriptString = <<<script
    require(["Magento_Sales/order/create/form"], function(){

script;
$scriptString .= "order.overlay('shipping-method-overlay', " . ($block->getQuote()->isVirtual() ? 'false' : 'true') .
    ');' . PHP_EOL;
$scriptString .= "order.overlay('address-shipping-overlay', " . ($block->getQuote()->isVirtual() ? 'false' : 'true') .
 ');' . PHP_EOL;
$scriptString .= "order.isOnlyVirtualProduct = " . ($block->getQuote()->isVirtual() ? 'true' : 'false') . ';' . PHP_EOL;
$scriptString .= <<<script

        AdminOrder.prototype.setAdminShippingMethod = function (method, description, price) {
            var data = {};
            data['order[shipping_method]'] = method;
            data['order[custom_description]'] = description;
            data['order[custom_price]'] = price;
            var decimalOnly = /^\s*-?[0-9]\d*(\.\d{1,2})?\s*$/;
            if (!decimalOnly.test(price)) {
                alert('Custom shipping price field can only contain price data');
                return false;
            }

            if (price < 0) {
                alert('Custom shipping price must be zero or greater');
                return false;
            }

            this.loadArea(['shipping_method', 'totals', 'billing_method'], true, data);
        }
script;
$scriptString .= <<<script
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
